'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, BarChart3, Bell, ChevronDown, Search, ShieldCheck, Wallet, X } from 'lucide-react';
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

type Asset={symbol:string;yahoo:string;name:string;type:'Acción'|'Cripto';price:number;change:number;color:string;currency:'USD'|'EUR'};
type Position={quantity:number;avgPrice:number};
const catalog:Asset[]=[
 {symbol:'AAPL',yahoo:'AAPL',name:'Apple',type:'Acción',price:226.84,change:1.12,color:'#d6d6d6',currency:'USD'},
 {symbol:'MSFT',yahoo:'MSFT',name:'Microsoft',type:'Acción',price:509.24,change:.68,color:'#60a5fa',currency:'USD'},
 {symbol:'NVDA',yahoo:'NVDA',name:'NVIDIA',type:'Acción',price:177.82,change:2.35,color:'#84cc16',currency:'USD'},
 {symbol:'AMZN',yahoo:'AMZN',name:'Amazon',type:'Acción',price:231.03,change:-.24,color:'#f59e0b',currency:'USD'},
 {symbol:'GOOGL',yahoo:'GOOGL',name:'Alphabet',type:'Acción',price:201.16,change:.91,color:'#ef4444',currency:'USD'},
 {symbol:'META',yahoo:'META',name:'Meta',type:'Acción',price:751.67,change:1.04,color:'#3b82f6',currency:'USD'},
 {symbol:'TSLA',yahoo:'TSLA',name:'Tesla',type:'Acción',price:350.84,change:-1.36,color:'#ef4444',currency:'USD'},
 {symbol:'NFLX',yahoo:'NFLX',name:'Netflix',type:'Acción',price:1210.44,change:.43,color:'#e50914',currency:'USD'},
 {symbol:'JPM',yahoo:'JPM',name:'JPMorgan',type:'Acción',price:287.12,change:.32,color:'#38bdf8',currency:'USD'},
 {symbol:'KO',yahoo:'KO',name:'Coca-Cola',type:'Acción',price:69.91,change:-.18,color:'#f87171',currency:'USD'},
 {symbol:'BTC',yahoo:'BTC-EUR',name:'Bitcoin',type:'Cripto',price:66842.31,change:2.84,color:'#f59e0b',currency:'EUR'},
 {symbol:'ETH',yahoo:'ETH-EUR',name:'Ethereum',type:'Cripto',price:3457.92,change:1.47,color:'#8b5cf6',currency:'EUR'},
 {symbol:'SOL',yahoo:'SOL-EUR',name:'Solana',type:'Cripto',price:148.26,change:-.73,color:'#14b8a6',currency:'EUR'},
 {symbol:'XRP',yahoo:'XRP-EUR',name:'XRP',type:'Cripto',price:2.74,change:.82,color:'#e2e8f0',currency:'EUR'},
 {symbol:'ADA',yahoo:'ADA-EUR',name:'Cardano',type:'Cripto',price:.74,change:-.35,color:'#38bdf8',currency:'EUR'},
 {symbol:'DOGE',yahoo:'DOGE-EUR',name:'Dogecoin',type:'Cripto',price:.22,change:1.66,color:'#facc15',currency:'EUR'},
];
const eur=new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:2});
const usd=new Intl.NumberFormat('es-ES',{style:'currency',currency:'USD',maximumFractionDigits:2});
const money=(value:number,currency:'USD'|'EUR')=>(currency==='EUR'?eur:usd).format(value);

export default function Home(){
 const [assets,setAssets]=useState(catalog);const [selected,setSelected]=useState('AAPL');const [filter,setFilter]=useState<'Todos'|'Acciones'|'Cripto'>('Todos');const [query,setQuery]=useState('');const [results,setResults]=useState<Asset[]>([]);const [searching,setSearching]=useState(false);
 const [side,setSide]=useState<'buy'|'sell'>('buy');const [amount,setAmount]=useState('250');const [cash,setCash]=useState(10000);const [positions,setPositions]=useState<Record<string,Position>>({});const [status,setStatus]=useState('Conectando mercado');const [toast,setToast]=useState('');
 const asset=assets.find(a=>a.symbol===selected)??assets[0];const amountNumber=Number(amount||0);const qty=amountNumber/asset.price;const held=positions[asset.symbol]?.quantity??0;
 useEffect(()=>{const saved=localStorage.getItem('practicatrade-v2');if(saved)try{const v=JSON.parse(saved);setCash(v.cash??10000);setPositions(v.positions??{})}catch{}},[]);
 useEffect(()=>{localStorage.setItem('practicatrade-v2',JSON.stringify({cash,positions}))},[cash,positions]);
 useEffect(()=>{async function refresh(){try{const symbols=catalog.map(a=>a.yahoo).join(',');const r=await fetch(`/api/market?symbols=${encodeURIComponent(symbols)}`);if(!r.ok)throw new Error();const live=await r.json();setAssets(current=>current.map(a=>live[a.yahoo]?{...a,price:live[a.yahoo].price,change:live[a.yahoo].change}:a));setStatus('Mercado actualizado')}catch{setStatus('Datos de respaldo')}}refresh();const id=setInterval(refresh,60000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(query.trim().length<2){setResults([]);setSearching(false);return}setSearching(true);const controller=new AbortController();const id=setTimeout(async()=>{try{const r=await fetch(`/api/market?q=${encodeURIComponent(query.trim())}`,{signal:controller.signal});const found=await r.json();setResults(found.map((a:Asset)=>({...a,color:a.type==='Cripto'?'#f59e0b':'#94a3b8'})))}catch{}finally{setSearching(false)}},350);return()=>{clearTimeout(id);controller.abort()}},[query]);
 const local=assets.filter(a=>(filter==='Todos'||(filter==='Acciones'?a.type==='Acción':a.type==='Cripto'))&&`${a.symbol} ${a.name}`.toLowerCase().includes(query.toLowerCase()));
 const visible=(query.trim().length>=2?[...local,...results.filter(r=>!assets.some(a=>a.yahoo===r.yahoo))]:local).filter(a=>filter==='Todos'||(filter==='Acciones'?a.type==='Acción':a.type==='Cripto'));
 function chooseAsset(a:Asset){if(!assets.some(x=>x.yahoo===a.yahoo))setAssets(current=>[a,...current]);setSelected(a.symbol);setQuery('')}
 const invested=Object.entries(positions).reduce((sum,[symbol,p])=>sum+p.quantity*(assets.find(a=>a.symbol===symbol)?.price??p.avgPrice),0);const total=cash+invested;
 const canTrade=amountNumber>0&&(side==='buy'?amountNumber<=cash:qty<=held);
 const chart=useMemo(()=>{const seed=[-.8,-.4,-.65,-.05,.2,.05,.55,.35,.8,1.1,.88,1.35,1.55,1.42,1.9];return seed.map((v,i)=>({time:`${i+8}:00`,price:asset.price*(1+(v-1.9)*Math.max(Math.abs(asset.change),.8)/100)}))},[asset]);
 function trade(){if(!canTrade)return;const prev=positions[asset.symbol]??{quantity:0,avgPrice:0};const nextQty=prev.quantity+(side==='buy'?qty:-qty);setCash(v=>v+(side==='buy'?-amountNumber:amountNumber));setPositions(p=>({...p,[asset.symbol]:{quantity:Math.max(0,nextQty),avgPrice:side==='buy'?(prev.quantity*prev.avgPrice+amountNumber)/(prev.quantity+qty):prev.avgPrice}}));setToast(`${side==='buy'?'Compra':'Venta'} ejecutada: ${qty.toFixed(6)} ${asset.symbol}`);setTimeout(()=>setToast(''),3500)}
 return <main className="min-h-screen bg-background text-foreground"><header className="border-b border-white/8 bg-[#0b111d]/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1540px] items-center justify-between px-4 sm:px-7"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-lime-300 text-[#091018]"><BarChart3 size={20}/></div><span className="text-lg font-bold">PRACTICA<span className="text-lime-300">TRADE</span></span><span className="hidden rounded-full border border-lime-300/20 bg-lime-300/8 px-2 py-1 text-[10px] font-bold uppercase tracking-[.14em] text-lime-300 sm:inline">{status}</span></div><div className="flex items-center gap-2"><Button variant="ghost" size="icon"><Bell/></Button><div className="grid size-8 place-items-center rounded-full bg-gradient-to-br from-violet-400 to-cyan-300 text-xs font-bold text-slate-950">AP</div></div></div></header>
 <div className="mx-auto grid max-w-[1540px] gap-5 px-4 py-5 sm:px-7 xl:grid-cols-[280px_minmax(0,1fr)_350px]">
  <aside className="rounded-2xl border border-white/8 bg-card p-4 xl:self-start"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-slate-500"/><Input value={query} onChange={e=>setQuery(e.target.value)} className="h-9 border-white/8 bg-white/[.035] pl-9" placeholder="Busca cualquier acción"/>{query&&<button onClick={()=>setQuery('')} className="absolute right-3 top-2.5"><X className="size-4 text-slate-500"/></button>}</div><p className="mt-2 min-h-4 text-[10px] text-slate-500">{searching?'Buscando en el mercado mundial…':query.length>=2?'Resultados del mercado':'Escribe un nombre o símbolo: SAN, Nike, BMW…'}</p><div className="my-3 flex rounded-lg bg-white/5 p-1">{(['Todos','Acciones','Cripto'] as const).map(v=><button key={v} onClick={()=>setFilter(v)} className={`flex-1 rounded-md py-1.5 text-xs ${filter===v?'bg-white/10 text-white':'text-slate-500'}`}>{v}</button>)}</div><div className="max-h-[620px] space-y-1 overflow-auto pr-1">{visible.map(a=><button onClick={()=>chooseAsset(a)} key={a.yahoo} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left ${selected===a.symbol?'border-lime-300/25 bg-lime-300/[.07]':'border-transparent hover:bg-white/5'}`}><span className="grid size-9 shrink-0 place-items-center rounded-full text-xs font-bold text-slate-950" style={{backgroundColor:a.color}}>{a.symbol[0]}</span><span className="min-w-0 flex-1"><b className="block text-sm">{a.symbol}</b><span className="block truncate text-xs text-slate-500">{a.name}</span></span><span className="text-right"><b className="block text-xs">{a.price?money(a.price,a.currency):'Consultar'}</b>{a.price>0&&<span className={`text-xs ${a.change>=0?'text-lime-300':'text-rose-400'}`}>{a.change>0?'+':''}{a.change.toFixed(2)}%</span>}</span></button>)}</div></aside>
  <section className="min-w-0 space-y-5"><div className="grid gap-3 sm:grid-cols-3">{[['Patrimonio',eur.format(total),`${Object.values(positions).filter(p=>p.quantity>0).length} posiciones`],['Efectivo',eur.format(cash),'Disponible para invertir'],['Invertido',eur.format(invested),'Valor de mercado']].map(([l,v,n])=><div key={l} className="rounded-2xl border border-white/8 bg-card p-4"><p className="text-xs text-slate-500">{l}</p><p className="mt-1 text-xl font-semibold">{v}</p><p className="mt-1 text-xs text-lime-300">{n}</p></div>)}</div>
   <div className="rounded-2xl border border-white/8 bg-card p-4 sm:p-6"><div className="mb-6 flex flex-wrap justify-between gap-4"><div><div className="flex items-center gap-2"><h1 className="text-xl font-bold">{asset.name}</h1><span className="rounded bg-white/5 px-2 py-1 text-[10px] text-slate-400">{asset.symbol} · {asset.type}</span></div><div className="mt-2 flex items-end gap-3"><span className="text-3xl font-semibold">{money(asset.price,asset.currency)}</span><span className={`mb-1 flex text-sm font-semibold ${asset.change>=0?'text-lime-300':'text-rose-400'}`}>{asset.change>=0?<ArrowUpRight size={16}/>:<ArrowDownRight size={16}/>} {Math.abs(asset.change).toFixed(2)}%</span></div></div><div className="flex rounded-lg bg-white/5 p-1">{['1D','1S','1M','1A'].map(r=><button key={r} className={`rounded-md px-3 py-1.5 text-xs ${r==='1D'?'bg-white/10':'text-slate-500'}`}>{r}</button>)}</div></div><div className="h-[330px]"><ResponsiveContainer><AreaChart data={chart}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#bef264" stopOpacity={.22}/><stop offset="1" stopColor="#bef264" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="time" axisLine={false} tickLine={false} tick={{fill:'#64748b',fontSize:11}} interval={3}/><YAxis domain={['dataMin','dataMax']} orientation="right" axisLine={false} tickLine={false} tick={{fill:'#64748b',fontSize:11}} width={65}/><Tooltip contentStyle={{background:'#111a28',border:'1px solid #263244',borderRadius:10}} formatter={v=>money(Number(v),asset.currency)}/><Area type="monotone" dataKey="price" stroke="#bef264" strokeWidth={2.4} fill="url(#fill)"/></AreaChart></ResponsiveContainer></div></div>
   {Object.values(positions).some(p=>p.quantity>0)&&<div className="rounded-2xl border border-white/8 bg-card p-5"><h2 className="mb-4 font-semibold">Tu cartera</h2><div className="space-y-3">{Object.entries(positions).filter(([,p])=>p.quantity>0).map(([s,p])=>{const a=assets.find(x=>x.symbol===s)!;return <button key={s} onClick={()=>setSelected(s)} className="flex w-full items-center justify-between rounded-xl bg-white/[.035] p-3 text-left"><span><b>{a.name}</b><small className="ml-2 text-slate-500">{p.quantity.toFixed(5)} {s}</small></span><b>{money(p.quantity*a.price,a.currency)}</b></button>})}</div></div>}
  </section>
  <aside className="rounded-2xl border border-white/8 bg-card p-5 xl:self-start"><div className="mb-5 flex rounded-xl bg-white/5 p-1"><button onClick={()=>setSide('buy')} className={`flex-1 rounded-lg py-2 text-sm font-semibold ${side==='buy'?'bg-lime-300 text-slate-950':'text-slate-400'}`}>Comprar</button><button onClick={()=>setSide('sell')} className={`flex-1 rounded-lg py-2 text-sm font-semibold ${side==='sell'?'bg-rose-400 text-slate-950':'text-slate-400'}`}>Vender</button></div><label className="text-xs text-slate-400">Activo seleccionado</label><button className="mt-2 flex h-11 w-full items-center justify-between rounded-xl border border-white/10 bg-white/[.035] px-3 text-sm"><span className="flex items-center gap-2"><span className="grid size-6 place-items-center rounded-full text-[10px] font-bold text-slate-950" style={{backgroundColor:asset.color}}>{asset.symbol[0]}</span>{asset.name}</span><ChevronDown size={16}/></button><div className="mt-5 flex justify-between"><label htmlFor="amount" className="text-xs text-slate-400">Importe</label><span className="text-xs text-slate-500">Saldo: {eur.format(cash)}</span></div><div className="relative mt-2"><Input id="amount" type="number" value={amount} onChange={e=>setAmount(e.target.value)} className="h-12 border-white/10 bg-white/[.035] pr-14 text-lg font-semibold"/><span className="absolute right-4 top-3.5 text-sm text-slate-500">EUR</span></div><div className="mt-2 flex gap-2">{['100','250','500'].map(v=><button key={v} onClick={()=>setAmount(v)} className="flex-1 rounded-lg bg-white/5 py-1.5 text-xs text-slate-400">{v} €</button>)}</div><div className="my-5 space-y-3 border-y border-white/8 py-4 text-sm"><div className="flex justify-between text-slate-400"><span>Precio</span><span className="text-white">{money(asset.price,asset.currency)}</span></div><div className="flex justify-between text-slate-400"><span>{side==='buy'?'Recibirás':'Venderás'}</span><span className="text-white">{qty.toFixed(6)} {asset.symbol}</span></div><div className="flex justify-between text-slate-400"><span>En cartera</span><span className="text-white">{held.toFixed(6)}</span></div></div><Button onClick={trade} disabled={!canTrade} className={`h-12 w-full font-bold ${side==='buy'?'bg-lime-300 text-slate-950':'bg-rose-400 text-slate-950'}`}>{side==='buy'?<ArrowUpRight/>:<ArrowDownRight/>}{side==='buy'?'Comprar':'Vender'} {asset.symbol}</Button><p className="mt-3 min-h-5 text-center text-xs text-lime-300">{toast}</p><div className="mt-3 flex items-center justify-center gap-2 text-[11px] text-slate-500"><Wallet size={13}/> Operación simulada · sin dinero real</div><div className="mt-5 rounded-xl border border-cyan-300/15 bg-cyan-300/[.04] p-3"><ShieldCheck className="mb-2 size-4 text-cyan-300"/><p className="text-xs leading-5 text-slate-400">Los precios pueden sufrir retrasos. Esta app es educativa y no ofrece asesoramiento financiero.</p></div></aside>
 </div></main>
}

